// GENERATED FILE — do not edit by hand.
// Run `node scripts/generate-countries.mjs` in evera-one to regenerate;
// it writes this file in both repos, so they cannot drift.
//
// Sources (see the generator for why each was chosen):
//   names + ISO 3166-1 alpha-2 — mledoze/countries (tracks the ISO standard)
//   dial codes — Google libphonenumber 1.13.13 (ITU-T E.164)
// 243 countries. Absent, having no ITU numbering of their
// own: Antarctica, Bouvet I., South Georgia, Heard & McDonald Is.,
// Pitcairn, French Southern Lands, US Minor Outlying Is.

export interface Country {
  /** ISO 3166-1 alpha-2, e.g. "AE". Unique — use as the React key. */
  iso2: string;
  /** Common English name, e.g. "United Arab Emirates". */
  name: string;
  /** ITU country calling code, e.g. "+971". NOT unique: +1 covers 25. */
  dialCode: string;
  flag: string;
  /** Alternate spellings, for search only — never displayed. */
  aliases: string[];
}

/** Every country, UAE first (home market), then alphabetical. */
export const COUNTRIES: Country[] = [
  { iso2: "AE", name: "United Arab Emirates", dialCode: "+971", flag: "🇦🇪", aliases: ["AE","UAE","Emirates","ARE"] },
  { iso2: "AF", name: "Afghanistan", dialCode: "+93", flag: "🇦🇫", aliases: ["Islamic Republic of Afghanistan","AF","Afġānistān","AFG"] },
  { iso2: "AX", name: "Åland Islands", dialCode: "+358", flag: "🇦🇽", aliases: ["AX","Aaland","Aland","Ahvenanmaa","ALA"] },
  { iso2: "AL", name: "Albania", dialCode: "+355", flag: "🇦🇱", aliases: ["Republic of Albania","AL","Shqipëri","Shqipëria","Shqipnia","ALB"] },
  { iso2: "DZ", name: "Algeria", dialCode: "+213", flag: "🇩🇿", aliases: ["People's Democratic Republic of Algeria","DZ","Dzayer","Algérie","DZA"] },
  { iso2: "AS", name: "American Samoa", dialCode: "+1", flag: "🇦🇸", aliases: ["AS","Amerika Sāmoa","Amelika Sāmoa","Sāmoa Amelika","ASM"] },
  { iso2: "AD", name: "Andorra", dialCode: "+376", flag: "🇦🇩", aliases: ["Principality of Andorra","AD","Principat d'Andorra","AND"] },
  { iso2: "AO", name: "Angola", dialCode: "+244", flag: "🇦🇴", aliases: ["Republic of Angola","AO","República de Angola","ʁɛpublika de an'ɡɔla","AGO"] },
  { iso2: "AI", name: "Anguilla", dialCode: "+1", flag: "🇦🇮", aliases: ["AI","AIA"] },
  { iso2: "AG", name: "Antigua and Barbuda", dialCode: "+1", flag: "🇦🇬", aliases: ["AG","ATG"] },
  { iso2: "AR", name: "Argentina", dialCode: "+54", flag: "🇦🇷", aliases: ["Argentine Republic","AR","República Argentina","ARG"] },
  { iso2: "AM", name: "Armenia", dialCode: "+374", flag: "🇦🇲", aliases: ["Republic of Armenia","AM","Hayastan","Հայաստանի Հանրապետություն","ARM"] },
  { iso2: "AW", name: "Aruba", dialCode: "+297", flag: "🇦🇼", aliases: ["AW","ABW"] },
  { iso2: "AU", name: "Australia", dialCode: "+61", flag: "🇦🇺", aliases: ["Commonwealth of Australia","AU","AUS"] },
  { iso2: "AT", name: "Austria", dialCode: "+43", flag: "🇦🇹", aliases: ["Republic of Austria","AT","Osterreich","Oesterreich","AUT"] },
  { iso2: "AZ", name: "Azerbaijan", dialCode: "+994", flag: "🇦🇿", aliases: ["Republic of Azerbaijan","AZ","Azərbaycan Respublikası","AZE"] },
  { iso2: "BS", name: "Bahamas", dialCode: "+1", flag: "🇧🇸", aliases: ["Commonwealth of the Bahamas","BS","BHS"] },
  { iso2: "BH", name: "Bahrain", dialCode: "+973", flag: "🇧🇭", aliases: ["Kingdom of Bahrain","BH","Mamlakat al-Baḥrayn","BHR"] },
  { iso2: "BD", name: "Bangladesh", dialCode: "+880", flag: "🇧🇩", aliases: ["People's Republic of Bangladesh","BD","Gônôprôjatôntri Bangladesh","BGD"] },
  { iso2: "BB", name: "Barbados", dialCode: "+1", flag: "🇧🇧", aliases: ["BB","BRB"] },
  { iso2: "BY", name: "Belarus", dialCode: "+375", flag: "🇧🇾", aliases: ["Republic of Belarus","BY","Bielaruś","Белоруссия","Республика Белоруссия","BLR"] },
  { iso2: "BE", name: "Belgium", dialCode: "+32", flag: "🇧🇪", aliases: ["Kingdom of Belgium","BE","België","Belgie","Belgien","Belgique","Koninkrijk België","Royaume de Belgique","Königreich Belgien","BEL"] },
  { iso2: "BZ", name: "Belize", dialCode: "+501", flag: "🇧🇿", aliases: ["BZ","BLZ"] },
  { iso2: "BJ", name: "Benin", dialCode: "+229", flag: "🇧🇯", aliases: ["Republic of Benin","BJ","République du Bénin","BEN"] },
  { iso2: "BM", name: "Bermuda", dialCode: "+1", flag: "🇧🇲", aliases: ["BM","The Islands of Bermuda","The Bermudas","Somers Isles","BMU"] },
  { iso2: "BT", name: "Bhutan", dialCode: "+975", flag: "🇧🇹", aliases: ["Kingdom of Bhutan","BT","BTN"] },
  { iso2: "BO", name: "Bolivia", dialCode: "+591", flag: "🇧🇴", aliases: ["Plurinational State of Bolivia","BO","Buliwya","Wuliwya","Bolivia, Plurinational State of","Estado Plurinacional de Bolivia","Buliwya Mamallaqta","Wuliwya Suyu","Tetã Volívia","BOL"] },
  { iso2: "BA", name: "Bosnia and Herzegovina", dialCode: "+387", flag: "🇧🇦", aliases: ["BA","Bosnia-Herzegovina","Босна и Херцеговина","BIH"] },
  { iso2: "BW", name: "Botswana", dialCode: "+267", flag: "🇧🇼", aliases: ["Republic of Botswana","BW","Lefatshe la Botswana","BWA"] },
  { iso2: "BR", name: "Brazil", dialCode: "+55", flag: "🇧🇷", aliases: ["Federative Republic of Brazil","BR","Brasil","República Federativa do Brasil","BRA"] },
  { iso2: "IO", name: "British Indian Ocean Territory", dialCode: "+246", flag: "🇮🇴", aliases: ["IO","IOT"] },
  { iso2: "VG", name: "British Virgin Islands", dialCode: "+1", flag: "🇻🇬", aliases: ["Virgin Islands","VG","Virgin Islands, British","VGB"] },
  { iso2: "BN", name: "Brunei", dialCode: "+673", flag: "🇧🇳", aliases: ["Nation of Brunei, Abode of Peace","BN","Brunei Darussalam","Nation of Brunei","the Abode of Peace","BRN"] },
  { iso2: "BG", name: "Bulgaria", dialCode: "+359", flag: "🇧🇬", aliases: ["Republic of Bulgaria","BG","Република България","BGR"] },
  { iso2: "BF", name: "Burkina Faso", dialCode: "+226", flag: "🇧🇫", aliases: ["BF","BFA"] },
  { iso2: "BI", name: "Burundi", dialCode: "+257", flag: "🇧🇮", aliases: ["Republic of Burundi","BI","Republika y'Uburundi","République du Burundi","BDI"] },
  { iso2: "KH", name: "Cambodia", dialCode: "+855", flag: "🇰🇭", aliases: ["Kingdom of Cambodia","KH","KHM"] },
  { iso2: "CM", name: "Cameroon", dialCode: "+237", flag: "🇨🇲", aliases: ["Republic of Cameroon","CM","République du Cameroun","CMR"] },
  { iso2: "CA", name: "Canada", dialCode: "+1", flag: "🇨🇦", aliases: ["CA","CAN"] },
  { iso2: "CV", name: "Cape Verde", dialCode: "+238", flag: "🇨🇻", aliases: ["Republic of Cabo Verde","CV","República de Cabo Verde","CPV"] },
  { iso2: "BQ", name: "Caribbean Netherlands", dialCode: "+599", flag: "🇧🇶", aliases: ["Bonaire, Sint Eustatius and Saba","BES islands","Bonaire Sint Eustatius and Saba","BES"] },
  { iso2: "KY", name: "Cayman Islands", dialCode: "+1", flag: "🇰🇾", aliases: ["KY","CYM"] },
  { iso2: "CF", name: "Central African Republic", dialCode: "+236", flag: "🇨🇫", aliases: ["CF","République centrafricaine","CAF"] },
  { iso2: "TD", name: "Chad", dialCode: "+235", flag: "🇹🇩", aliases: ["Republic of Chad","TD","Tchad","République du Tchad","TCD"] },
  { iso2: "CL", name: "Chile", dialCode: "+56", flag: "🇨🇱", aliases: ["Republic of Chile","CL","República de Chile","CHL"] },
  { iso2: "CN", name: "China", dialCode: "+86", flag: "🇨🇳", aliases: ["People's Republic of China","CN","Zhōngguó","Zhongguo","Zhonghua","中华人民共和国","Zhōnghuá Rénmín Gònghéguó","CHN"] },
  { iso2: "CX", name: "Christmas Island", dialCode: "+61", flag: "🇨🇽", aliases: ["Territory of Christmas Island","CX","CXR"] },
  { iso2: "CC", name: "Cocos (Keeling) Islands", dialCode: "+61", flag: "🇨🇨", aliases: ["Territory of the Cocos (Keeling) Islands","CC","Keeling Islands","Cocos Islands","CCK"] },
  { iso2: "CO", name: "Colombia", dialCode: "+57", flag: "🇨🇴", aliases: ["Republic of Colombia","CO","República de Colombia","COL"] },
  { iso2: "KM", name: "Comoros", dialCode: "+269", flag: "🇰🇲", aliases: ["Union of the Comoros","KM","Union des Comores","Udzima wa Komori","al-Ittiḥād al-Qumurī","COM"] },
  { iso2: "CG", name: "Congo", dialCode: "+242", flag: "🇨🇬", aliases: ["Republic of the Congo","CG","Congo-Brazzaville","COG"] },
  { iso2: "CK", name: "Cook Islands", dialCode: "+682", flag: "🇨🇰", aliases: ["CK","Kūki 'Āirani","COK"] },
  { iso2: "CR", name: "Costa Rica", dialCode: "+506", flag: "🇨🇷", aliases: ["Republic of Costa Rica","CR","República de Costa Rica","CRI"] },
  { iso2: "HR", name: "Croatia", dialCode: "+385", flag: "🇭🇷", aliases: ["Republic of Croatia","HR","Hrvatska","Republika Hrvatska","HRV"] },
  { iso2: "CU", name: "Cuba", dialCode: "+53", flag: "🇨🇺", aliases: ["Republic of Cuba","CU","República de Cuba","CUB"] },
  { iso2: "CW", name: "Curaçao", dialCode: "+599", flag: "🇨🇼", aliases: ["Country of Curaçao","CW","Curacao","Kòrsou","Land Curaçao","Pais Kòrsou","CUW"] },
  { iso2: "CY", name: "Cyprus", dialCode: "+357", flag: "🇨🇾", aliases: ["Republic of Cyprus","CY","Kýpros","Kıbrıs","Κυπριακή Δημοκρατία","Kıbrıs Cumhuriyeti","CYP"] },
  { iso2: "CZ", name: "Czechia", dialCode: "+420", flag: "🇨🇿", aliases: ["Czech Republic","CZ","Česká republika","Česko","CZE"] },
  { iso2: "DK", name: "Denmark", dialCode: "+45", flag: "🇩🇰", aliases: ["Kingdom of Denmark","DK","Danmark","Kongeriget Danmark","DNK"] },
  { iso2: "DJ", name: "Djibouti", dialCode: "+253", flag: "🇩🇯", aliases: ["Republic of Djibouti","DJ","Jabuuti","Gabuuti","République de Djibouti","Gabuutih Ummuuno","Jamhuuriyadda Jabuuti","DJI"] },
  { iso2: "DM", name: "Dominica", dialCode: "+1", flag: "🇩🇲", aliases: ["Commonwealth of Dominica","DM","Dominique","Wai‘tu kubuli","DMA"] },
  { iso2: "DO", name: "Dominican Republic", dialCode: "+1", flag: "🇩🇴", aliases: ["DO","DOM"] },
  { iso2: "CD", name: "DR Congo", dialCode: "+243", flag: "🇨🇩", aliases: ["Democratic Republic of the Congo","CD","Congo-Kinshasa","Congo, the Democratic Republic of the","Democratic Republic of Congo","DRC","COD"] },
  { iso2: "EC", name: "Ecuador", dialCode: "+593", flag: "🇪🇨", aliases: ["Republic of Ecuador","EC","República del Ecuador","ECU"] },
  { iso2: "EG", name: "Egypt", dialCode: "+20", flag: "🇪🇬", aliases: ["Arab Republic of Egypt","EG","EGY"] },
  { iso2: "SV", name: "El Salvador", dialCode: "+503", flag: "🇸🇻", aliases: ["Republic of El Salvador","SV","República de El Salvador","SLV"] },
  { iso2: "GQ", name: "Equatorial Guinea", dialCode: "+240", flag: "🇬🇶", aliases: ["Republic of Equatorial Guinea","GQ","República de Guinea Ecuatorial","République de Guinée équatoriale","República da Guiné Equatorial","GNQ"] },
  { iso2: "ER", name: "Eritrea", dialCode: "+291", flag: "🇪🇷", aliases: ["State of Eritrea","ER","ሃገረ ኤርትራ","Dawlat Iritriyá","ʾErtrā","Iritriyā","ERI"] },
  { iso2: "EE", name: "Estonia", dialCode: "+372", flag: "🇪🇪", aliases: ["Republic of Estonia","EE","Eesti","Eesti Vabariik","EST"] },
  { iso2: "SZ", name: "Eswatini", dialCode: "+268", flag: "🇸🇿", aliases: ["Kingdom of Eswatini","SZ","Swaziland","weSwatini","Swatini","Ngwane","Umbuso weSwatini","SWZ"] },
  { iso2: "ET", name: "Ethiopia", dialCode: "+251", flag: "🇪🇹", aliases: ["Federal Democratic Republic of Ethiopia","ET","ʾĪtyōṗṗyā","የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ","ETH"] },
  { iso2: "FK", name: "Falkland Islands", dialCode: "+500", flag: "🇫🇰", aliases: ["FK","Islas Malvinas","Falkland Islands (Malvinas)","FLK"] },
  { iso2: "FO", name: "Faroe Islands", dialCode: "+298", flag: "🇫🇴", aliases: ["FO","Føroyar","Færøerne","Faeroe Islands","FRO"] },
  { iso2: "FJ", name: "Fiji", dialCode: "+679", flag: "🇫🇯", aliases: ["Republic of Fiji","FJ","Viti","Matanitu ko Viti","Fijī Gaṇarājya","FJI"] },
  { iso2: "FI", name: "Finland", dialCode: "+358", flag: "🇫🇮", aliases: ["Republic of Finland","FI","Suomi","Suomen tasavalta","Republiken Finland","FIN"] },
  { iso2: "FR", name: "France", dialCode: "+33", flag: "🇫🇷", aliases: ["French Republic","FR","République française","FRA"] },
  { iso2: "GF", name: "French Guiana", dialCode: "+594", flag: "🇬🇫", aliases: ["Guiana","GF","Guyane","GUF"] },
  { iso2: "PF", name: "French Polynesia", dialCode: "+689", flag: "🇵🇫", aliases: ["PF","Polynésie française","Pōrīnetia Farāni","PYF"] },
  { iso2: "GA", name: "Gabon", dialCode: "+241", flag: "🇬🇦", aliases: ["Gabonese Republic","GA","République Gabonaise","GAB"] },
  { iso2: "GM", name: "Gambia", dialCode: "+220", flag: "🇬🇲", aliases: ["Republic of the Gambia","GM","GMB"] },
  { iso2: "GE", name: "Georgia", dialCode: "+995", flag: "🇬🇪", aliases: ["GE","Sakartvelo","GEO"] },
  { iso2: "DE", name: "Germany", dialCode: "+49", flag: "🇩🇪", aliases: ["Federal Republic of Germany","DE","Bundesrepublik Deutschland","DEU"] },
  { iso2: "GH", name: "Ghana", dialCode: "+233", flag: "🇬🇭", aliases: ["Republic of Ghana","GH","GHA"] },
  { iso2: "GI", name: "Gibraltar", dialCode: "+350", flag: "🇬🇮", aliases: ["GI","GIB"] },
  { iso2: "GR", name: "Greece", dialCode: "+30", flag: "🇬🇷", aliases: ["Hellenic Republic","GR","Elláda","Ελληνική Δημοκρατία","GRC"] },
  { iso2: "GL", name: "Greenland", dialCode: "+299", flag: "🇬🇱", aliases: ["GL","Grønland","GRL"] },
  { iso2: "GD", name: "Grenada", dialCode: "+1", flag: "🇬🇩", aliases: ["GD","GRD"] },
  { iso2: "GP", name: "Guadeloupe", dialCode: "+590", flag: "🇬🇵", aliases: ["GP","Gwadloup","GLP"] },
  { iso2: "GU", name: "Guam", dialCode: "+1", flag: "🇬🇺", aliases: ["GU","Guåhån","GUM"] },
  { iso2: "GT", name: "Guatemala", dialCode: "+502", flag: "🇬🇹", aliases: ["Republic of Guatemala","GT","GTM"] },
  { iso2: "GG", name: "Guernsey", dialCode: "+44", flag: "🇬🇬", aliases: ["Bailiwick of Guernsey","GG","Bailliage de Guernesey","GGY"] },
  { iso2: "GN", name: "Guinea", dialCode: "+224", flag: "🇬🇳", aliases: ["Republic of Guinea","GN","République de Guinée","GIN"] },
  { iso2: "GW", name: "Guinea-Bissau", dialCode: "+245", flag: "🇬🇼", aliases: ["Republic of Guinea-Bissau","GW","República da Guiné-Bissau","GNB"] },
  { iso2: "GY", name: "Guyana", dialCode: "+592", flag: "🇬🇾", aliases: ["Co-operative Republic of Guyana","GY","GUY"] },
  { iso2: "HT", name: "Haiti", dialCode: "+509", flag: "🇭🇹", aliases: ["Republic of Haiti","HT","République d'Haïti","Repiblik Ayiti","HTI"] },
  { iso2: "HN", name: "Honduras", dialCode: "+504", flag: "🇭🇳", aliases: ["Republic of Honduras","HN","República de Honduras","HND"] },
  { iso2: "HK", name: "Hong Kong", dialCode: "+852", flag: "🇭🇰", aliases: ["Hong Kong Special Administrative Region of the People's Republic of China","HK","HKG"] },
  { iso2: "HU", name: "Hungary", dialCode: "+36", flag: "🇭🇺", aliases: ["HU","HUN"] },
  { iso2: "IS", name: "Iceland", dialCode: "+354", flag: "🇮🇸", aliases: ["IS","Island","Republic of Iceland","Lýðveldið Ísland","ISL"] },
  { iso2: "IN", name: "India", dialCode: "+91", flag: "🇮🇳", aliases: ["Republic of India","IN","Bhārat","Bharat Ganrajya","இந்தியா","IND"] },
  { iso2: "ID", name: "Indonesia", dialCode: "+62", flag: "🇮🇩", aliases: ["Republic of Indonesia","ID","Republik Indonesia","IDN"] },
  { iso2: "IR", name: "Iran", dialCode: "+98", flag: "🇮🇷", aliases: ["Islamic Republic of Iran","IR","Iran, Islamic Republic of","Jomhuri-ye Eslāmi-ye Irān","IRN"] },
  { iso2: "IQ", name: "Iraq", dialCode: "+964", flag: "🇮🇶", aliases: ["Republic of Iraq","IQ","Jumhūriyyat al-‘Irāq","IRQ"] },
  { iso2: "IE", name: "Ireland", dialCode: "+353", flag: "🇮🇪", aliases: ["Republic of Ireland","IE","Éire","Poblacht na hÉireann","IRL"] },
  { iso2: "IM", name: "Isle of Man", dialCode: "+44", flag: "🇮🇲", aliases: ["IM","Ellan Vannin","Mann","Mannin","IMN"] },
  { iso2: "IL", name: "Israel", dialCode: "+972", flag: "🇮🇱", aliases: ["State of Israel","IL","Medīnat Yisrā'el","ISR"] },
  { iso2: "IT", name: "Italy", dialCode: "+39", flag: "🇮🇹", aliases: ["Italian Republic","IT","Repubblica italiana","ITA"] },
  { iso2: "CI", name: "Ivory Coast", dialCode: "+225", flag: "🇨🇮", aliases: ["Republic of Côte d'Ivoire","CI","Côte d'Ivoire","Cote d'Ivoire","République de Côte d'Ivoire","CIV"] },
  { iso2: "JM", name: "Jamaica", dialCode: "+1", flag: "🇯🇲", aliases: ["JM","JAM"] },
  { iso2: "JP", name: "Japan", dialCode: "+81", flag: "🇯🇵", aliases: ["JP","Nippon","Nihon","JPN"] },
  { iso2: "JE", name: "Jersey", dialCode: "+44", flag: "🇯🇪", aliases: ["Bailiwick of Jersey","JE","Bailliage de Jersey","Bailliage dé Jèrri","JEY"] },
  { iso2: "JO", name: "Jordan", dialCode: "+962", flag: "🇯🇴", aliases: ["Hashemite Kingdom of Jordan","JO","al-Mamlakah al-Urdunīyah al-Hāshimīyah","JOR"] },
  { iso2: "KZ", name: "Kazakhstan", dialCode: "+7", flag: "🇰🇿", aliases: ["Republic of Kazakhstan","KZ","Qazaqstan","Казахстан","Қазақстан Республикасы","Qazaqstan Respublïkası","Республика Казахстан","Respublika Kazakhstan","KAZ"] },
  { iso2: "KE", name: "Kenya", dialCode: "+254", flag: "🇰🇪", aliases: ["Republic of Kenya","KE","Jamhuri ya Kenya","KEN"] },
  { iso2: "KI", name: "Kiribati", dialCode: "+686", flag: "🇰🇮", aliases: ["Independent and Sovereign Republic of Kiribati","KI","Republic of Kiribati","Ribaberiki Kiribati","KIR"] },
  { iso2: "XK", name: "Kosovo", dialCode: "+383", flag: "🇽🇰", aliases: ["Republic of Kosovo","XK","Република Косово","UNK"] },
  { iso2: "KW", name: "Kuwait", dialCode: "+965", flag: "🇰🇼", aliases: ["State of Kuwait","KW","Dawlat al-Kuwait","KWT"] },
  { iso2: "KG", name: "Kyrgyzstan", dialCode: "+996", flag: "🇰🇬", aliases: ["Kyrgyz Republic","KG","Киргизия","Кыргыз Республикасы","Kyrgyz Respublikasy","KGZ"] },
  { iso2: "LA", name: "Laos", dialCode: "+856", flag: "🇱🇦", aliases: ["Lao People's Democratic Republic","LA","Lao","Sathalanalat Paxathipatai Paxaxon Lao","LAO"] },
  { iso2: "LV", name: "Latvia", dialCode: "+371", flag: "🇱🇻", aliases: ["Republic of Latvia","LV","Latvijas Republika","LVA"] },
  { iso2: "LB", name: "Lebanon", dialCode: "+961", flag: "🇱🇧", aliases: ["Lebanese Republic","LB","Al-Jumhūrīyah Al-Libnānīyah","LBN"] },
  { iso2: "LS", name: "Lesotho", dialCode: "+266", flag: "🇱🇸", aliases: ["Kingdom of Lesotho","LS","Muso oa Lesotho","LSO"] },
  { iso2: "LR", name: "Liberia", dialCode: "+231", flag: "🇱🇷", aliases: ["Republic of Liberia","LR","LBR"] },
  { iso2: "LY", name: "Libya", dialCode: "+218", flag: "🇱🇾", aliases: ["State of Libya","LY","Dawlat Libya","LBY"] },
  { iso2: "LI", name: "Liechtenstein", dialCode: "+423", flag: "🇱🇮", aliases: ["Principality of Liechtenstein","LI","Fürstentum Liechtenstein","LIE"] },
  { iso2: "LT", name: "Lithuania", dialCode: "+370", flag: "🇱🇹", aliases: ["Republic of Lithuania","LT","Lietuvos Respublika","LTU"] },
  { iso2: "LU", name: "Luxembourg", dialCode: "+352", flag: "🇱🇺", aliases: ["Grand Duchy of Luxembourg","LU","Grand-Duché de Luxembourg","Großherzogtum Luxemburg","Groussherzogtum Lëtzebuerg","LUX"] },
  { iso2: "MO", name: "Macau", dialCode: "+853", flag: "🇲🇴", aliases: ["Macao Special Administrative Region of the People's Republic of China","MO","澳门","Macao","中華人民共和國澳門特別行政區","Região Administrativa Especial de Macau da República Popular da China","MAC"] },
  { iso2: "MG", name: "Madagascar", dialCode: "+261", flag: "🇲🇬", aliases: ["Republic of Madagascar","MG","Repoblikan'i Madagasikara","République de Madagascar","MDG"] },
  { iso2: "MW", name: "Malawi", dialCode: "+265", flag: "🇲🇼", aliases: ["Republic of Malawi","MW","MWI"] },
  { iso2: "MY", name: "Malaysia", dialCode: "+60", flag: "🇲🇾", aliases: ["MY","MYS"] },
  { iso2: "MV", name: "Maldives", dialCode: "+960", flag: "🇲🇻", aliases: ["Republic of the Maldives","MV","Maldive Islands","Dhivehi Raajjeyge Jumhooriyya","MDV"] },
  { iso2: "ML", name: "Mali", dialCode: "+223", flag: "🇲🇱", aliases: ["Republic of Mali","ML","République du Mali","MLI"] },
  { iso2: "MT", name: "Malta", dialCode: "+356", flag: "🇲🇹", aliases: ["Republic of Malta","MT","Repubblika ta' Malta","MLT"] },
  { iso2: "MH", name: "Marshall Islands", dialCode: "+692", flag: "🇲🇭", aliases: ["Republic of the Marshall Islands","MH","Aolepān Aorōkin M̧ajeļ","MHL"] },
  { iso2: "MQ", name: "Martinique", dialCode: "+596", flag: "🇲🇶", aliases: ["MQ","MTQ"] },
  { iso2: "MR", name: "Mauritania", dialCode: "+222", flag: "🇲🇷", aliases: ["Islamic Republic of Mauritania","MR","al-Jumhūriyyah al-ʾIslāmiyyah al-Mūrītāniyyah","MRT"] },
  { iso2: "MU", name: "Mauritius", dialCode: "+230", flag: "🇲🇺", aliases: ["Republic of Mauritius","MU","République de Maurice","MUS"] },
  { iso2: "YT", name: "Mayotte", dialCode: "+262", flag: "🇾🇹", aliases: ["Department of Mayotte","YT","Département de Mayotte","MYT"] },
  { iso2: "MX", name: "Mexico", dialCode: "+52", flag: "🇲🇽", aliases: ["United Mexican States","MX","Mexicanos","Estados Unidos Mexicanos","MEX"] },
  { iso2: "FM", name: "Micronesia", dialCode: "+691", flag: "🇫🇲", aliases: ["Federated States of Micronesia","FM","Micronesia, Federated States of","FSM"] },
  { iso2: "MD", name: "Moldova", dialCode: "+373", flag: "🇲🇩", aliases: ["Republic of Moldova","MD","Moldova, Republic of","Republica Moldova","MDA"] },
  { iso2: "MC", name: "Monaco", dialCode: "+377", flag: "🇲🇨", aliases: ["Principality of Monaco","MC","Principauté de Monaco","MCO"] },
  { iso2: "MN", name: "Mongolia", dialCode: "+976", flag: "🇲🇳", aliases: ["MN","MNG"] },
  { iso2: "ME", name: "Montenegro", dialCode: "+382", flag: "🇲🇪", aliases: ["ME","Crna Gora","MNE"] },
  { iso2: "MS", name: "Montserrat", dialCode: "+1", flag: "🇲🇸", aliases: ["MS","MSR"] },
  { iso2: "MA", name: "Morocco", dialCode: "+212", flag: "🇲🇦", aliases: ["Kingdom of Morocco","MA","Al-Mamlakah al-Maġribiyah","MAR"] },
  { iso2: "MZ", name: "Mozambique", dialCode: "+258", flag: "🇲🇿", aliases: ["Republic of Mozambique","MZ","República de Moçambique","MOZ"] },
  { iso2: "MM", name: "Myanmar", dialCode: "+95", flag: "🇲🇲", aliases: ["Republic of the Union of Myanmar","MM","Burma","Pyidaunzu Thanmăda Myăma Nainngandaw","MMR"] },
  { iso2: "NA", name: "Namibia", dialCode: "+264", flag: "🇳🇦", aliases: ["Republic of Namibia","NA","Namibië","NAM"] },
  { iso2: "NR", name: "Nauru", dialCode: "+674", flag: "🇳🇷", aliases: ["Republic of Nauru","NR","Naoero","Pleasant Island","Ripublik Naoero","NRU"] },
  { iso2: "NP", name: "Nepal", dialCode: "+977", flag: "🇳🇵", aliases: ["Federal Democratic Republic of Nepal","NP","Loktāntrik Ganatantra Nepāl","NPL"] },
  { iso2: "NL", name: "Netherlands", dialCode: "+31", flag: "🇳🇱", aliases: ["Kingdom of the Netherlands","NL","Holland","Nederland","The Netherlands","NLD"] },
  { iso2: "NC", name: "New Caledonia", dialCode: "+687", flag: "🇳🇨", aliases: ["NC","NCL"] },
  { iso2: "NZ", name: "New Zealand", dialCode: "+64", flag: "🇳🇿", aliases: ["NZ","Aotearoa","NZL"] },
  { iso2: "NI", name: "Nicaragua", dialCode: "+505", flag: "🇳🇮", aliases: ["Republic of Nicaragua","NI","República de Nicaragua","NIC"] },
  { iso2: "NE", name: "Niger", dialCode: "+227", flag: "🇳🇪", aliases: ["Republic of Niger","NE","Nijar","NER"] },
  { iso2: "NG", name: "Nigeria", dialCode: "+234", flag: "🇳🇬", aliases: ["Federal Republic of Nigeria","NG","Nijeriya","Naíjíríà","NGA"] },
  { iso2: "NU", name: "Niue", dialCode: "+683", flag: "🇳🇺", aliases: ["NU","NIU"] },
  { iso2: "NF", name: "Norfolk Island", dialCode: "+672", flag: "🇳🇫", aliases: ["Territory of Norfolk Island","NF","Teratri of Norf'k Ailen","NFK"] },
  { iso2: "KP", name: "North Korea", dialCode: "+850", flag: "🇰🇵", aliases: ["Democratic People's Republic of Korea","KP","DPRK","조선민주주의인민공화국","Chosŏn Minjujuŭi Inmin Konghwaguk","Korea, Democratic People's Republic of","북한","북조선","PRK"] },
  { iso2: "MK", name: "North Macedonia", dialCode: "+389", flag: "🇲🇰", aliases: ["Republic of North Macedonia","MK","The former Yugoslav Republic of Macedonia","Macedonia, The Former Yugoslav Republic of","Република Северна Македонија","Macedonia","MKD"] },
  { iso2: "MP", name: "Northern Mariana Islands", dialCode: "+1", flag: "🇲🇵", aliases: ["Commonwealth of the Northern Mariana Islands","MP","Sankattan Siha Na Islas Mariånas","MNP"] },
  { iso2: "NO", name: "Norway", dialCode: "+47", flag: "🇳🇴", aliases: ["Kingdom of Norway","NO","Norge","Noreg","Kongeriket Norge","Kongeriket Noreg","NOR"] },
  { iso2: "OM", name: "Oman", dialCode: "+968", flag: "🇴🇲", aliases: ["Sultanate of Oman","OM","Salṭanat ʻUmān","OMN"] },
  { iso2: "PK", name: "Pakistan", dialCode: "+92", flag: "🇵🇰", aliases: ["Islamic Republic of Pakistan","PK","Pākistān","Islāmī Jumhūriya'eh Pākistān","PAK"] },
  { iso2: "PW", name: "Palau", dialCode: "+680", flag: "🇵🇼", aliases: ["Republic of Palau","PW","Beluu er a Belau","PLW"] },
  { iso2: "PS", name: "Palestine", dialCode: "+970", flag: "🇵🇸", aliases: ["State of Palestine","PS","Palestine, State of","Dawlat Filasṭin","PSE"] },
  { iso2: "PA", name: "Panama", dialCode: "+507", flag: "🇵🇦", aliases: ["Republic of Panama","PA","República de Panamá","PAN"] },
  { iso2: "PG", name: "Papua New Guinea", dialCode: "+675", flag: "🇵🇬", aliases: ["Independent State of Papua New Guinea","PG","Independen Stet bilong Papua Niugini","PNG"] },
  { iso2: "PY", name: "Paraguay", dialCode: "+595", flag: "🇵🇾", aliases: ["Republic of Paraguay","PY","República del Paraguay","Tetã Paraguái","PRY"] },
  { iso2: "PE", name: "Peru", dialCode: "+51", flag: "🇵🇪", aliases: ["Republic of Peru","PE","República del Perú","PER"] },
  { iso2: "PH", name: "Philippines", dialCode: "+63", flag: "🇵🇭", aliases: ["Republic of the Philippines","PH","Repúblika ng Pilipinas","PHL"] },
  { iso2: "PL", name: "Poland", dialCode: "+48", flag: "🇵🇱", aliases: ["Republic of Poland","PL","Rzeczpospolita Polska","POL"] },
  { iso2: "PT", name: "Portugal", dialCode: "+351", flag: "🇵🇹", aliases: ["Portuguese Republic","PT","Portuguesa","República Portuguesa","PRT"] },
  { iso2: "PR", name: "Puerto Rico", dialCode: "+1", flag: "🇵🇷", aliases: ["Commonwealth of Puerto Rico","PR","Estado Libre Asociado de Puerto Rico","PRI"] },
  { iso2: "QA", name: "Qatar", dialCode: "+974", flag: "🇶🇦", aliases: ["State of Qatar","QA","Dawlat Qaṭar","QAT"] },
  { iso2: "RE", name: "Réunion", dialCode: "+262", flag: "🇷🇪", aliases: ["Réunion Island","RE","Reunion","REU"] },
  { iso2: "RO", name: "Romania", dialCode: "+40", flag: "🇷🇴", aliases: ["RO","Rumania","Roumania","România","ROU"] },
  { iso2: "RU", name: "Russia", dialCode: "+7", flag: "🇷🇺", aliases: ["Russian Federation","RU","Российская Федерация","RUS"] },
  { iso2: "RW", name: "Rwanda", dialCode: "+250", flag: "🇷🇼", aliases: ["Republic of Rwanda","RW","Repubulika y'u Rwanda","République du Rwanda","RWA"] },
  { iso2: "BL", name: "Saint Barthélemy", dialCode: "+590", flag: "🇧🇱", aliases: ["Collectivity of Saint Barthélemy","BL","St. Barthelemy","Collectivité de Saint-Barthélemy","BLM"] },
  { iso2: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", dialCode: "+290", flag: "🇸🇭", aliases: ["Saint Helena","St. Helena, Ascension and Tristan da Cunha","SHN"] },
  { iso2: "KN", name: "Saint Kitts and Nevis", dialCode: "+1", flag: "🇰🇳", aliases: ["Federation of Saint Christopher and Nevis","KN","KNA"] },
  { iso2: "LC", name: "Saint Lucia", dialCode: "+1", flag: "🇱🇨", aliases: ["LC","LCA"] },
  { iso2: "MF", name: "Saint Martin", dialCode: "+590", flag: "🇲🇫", aliases: ["MF","Collectivity of Saint Martin","Collectivité de Saint-Martin","Saint Martin (French part)","MAF"] },
  { iso2: "PM", name: "Saint Pierre and Miquelon", dialCode: "+508", flag: "🇵🇲", aliases: ["PM","Collectivité territoriale de Saint-Pierre-et-Miquelon","SPM"] },
  { iso2: "VC", name: "Saint Vincent and the Grenadines", dialCode: "+1", flag: "🇻🇨", aliases: ["VC","VCT"] },
  { iso2: "WS", name: "Samoa", dialCode: "+685", flag: "🇼🇸", aliases: ["Independent State of Samoa","WS","Malo Saʻoloto Tutoʻatasi o Sāmoa","WSM"] },
  { iso2: "SM", name: "San Marino", dialCode: "+378", flag: "🇸🇲", aliases: ["Most Serene Republic of San Marino","SM","Republic of San Marino","Repubblica di San Marino","SMR"] },
  { iso2: "ST", name: "São Tomé and Príncipe", dialCode: "+239", flag: "🇸🇹", aliases: ["Democratic Republic of São Tomé and Príncipe","ST","Sao Tome and Principe","República Democrática de São Tomé e Príncipe","STP"] },
  { iso2: "SA", name: "Saudi Arabia", dialCode: "+966", flag: "🇸🇦", aliases: ["Kingdom of Saudi Arabia","Saudi","SA","Al-Mamlakah al-‘Arabiyyah as-Su‘ūdiyyah","SAU"] },
  { iso2: "SN", name: "Senegal", dialCode: "+221", flag: "🇸🇳", aliases: ["Republic of Senegal","SN","République du Sénégal","SEN"] },
  { iso2: "RS", name: "Serbia", dialCode: "+381", flag: "🇷🇸", aliases: ["Republic of Serbia","RS","Srbija","Republika Srbija","Србија","Република Србија","SRB"] },
  { iso2: "SC", name: "Seychelles", dialCode: "+248", flag: "🇸🇨", aliases: ["Republic of Seychelles","SC","Repiblik Sesel","République des Seychelles","SYC"] },
  { iso2: "SL", name: "Sierra Leone", dialCode: "+232", flag: "🇸🇱", aliases: ["Republic of Sierra Leone","SL","SLE"] },
  { iso2: "SG", name: "Singapore", dialCode: "+65", flag: "🇸🇬", aliases: ["Republic of Singapore","SG","Singapura","Republik Singapura","新加坡共和国","SGP"] },
  { iso2: "SX", name: "Sint Maarten", dialCode: "+1", flag: "🇸🇽", aliases: ["SX","Sint Maarten (Dutch part)","SXM"] },
  { iso2: "SK", name: "Slovakia", dialCode: "+421", flag: "🇸🇰", aliases: ["Slovak Republic","SK","Slovenská republika","SVK"] },
  { iso2: "SI", name: "Slovenia", dialCode: "+386", flag: "🇸🇮", aliases: ["Republic of Slovenia","SI","Republika Slovenija","SVN"] },
  { iso2: "SB", name: "Solomon Islands", dialCode: "+677", flag: "🇸🇧", aliases: ["SB","SLB"] },
  { iso2: "SO", name: "Somalia", dialCode: "+252", flag: "🇸🇴", aliases: ["Federal Republic of Somalia","SO","aṣ-Ṣūmāl","Jamhuuriyadda Federaalka Soomaaliya","Jumhūriyyat aṣ-Ṣūmāl al-Fiderāliyya","SOM"] },
  { iso2: "ZA", name: "South Africa", dialCode: "+27", flag: "🇿🇦", aliases: ["Republic of South Africa","ZA","RSA","Suid-Afrika","ZAF"] },
  { iso2: "KR", name: "South Korea", dialCode: "+82", flag: "🇰🇷", aliases: ["Republic of Korea","KR","Korea, Republic of","남한","남조선","KOR"] },
  { iso2: "SS", name: "South Sudan", dialCode: "+211", flag: "🇸🇸", aliases: ["Republic of South Sudan","SS","SSD"] },
  { iso2: "ES", name: "Spain", dialCode: "+34", flag: "🇪🇸", aliases: ["Kingdom of Spain","ES","Reino de España","ESP"] },
  { iso2: "LK", name: "Sri Lanka", dialCode: "+94", flag: "🇱🇰", aliases: ["Democratic Socialist Republic of Sri Lanka","LK","ilaṅkai","LKA"] },
  { iso2: "SD", name: "Sudan", dialCode: "+249", flag: "🇸🇩", aliases: ["Republic of the Sudan","SD","Jumhūrīyat as-Sūdān","SDN"] },
  { iso2: "SR", name: "Suriname", dialCode: "+597", flag: "🇸🇷", aliases: ["Republic of Suriname","SR","Sarnam","Sranangron","Republiek Suriname","SUR"] },
  { iso2: "SJ", name: "Svalbard and Jan Mayen", dialCode: "+47", flag: "🇸🇯", aliases: ["Svalbard og Jan Mayen","SJ","Svalbard and Jan Mayen Islands","SJM"] },
  { iso2: "SE", name: "Sweden", dialCode: "+46", flag: "🇸🇪", aliases: ["Kingdom of Sweden","SE","Konungariket Sverige","SWE"] },
  { iso2: "CH", name: "Switzerland", dialCode: "+41", flag: "🇨🇭", aliases: ["Swiss Confederation","CH","Schweiz","Suisse","Svizzera","Svizra","CHE"] },
  { iso2: "SY", name: "Syria", dialCode: "+963", flag: "🇸🇾", aliases: ["Syrian Arab Republic","SY","Al-Jumhūrīyah Al-ʻArabīyah As-Sūrīyah","SYR"] },
  { iso2: "TW", name: "Taiwan", dialCode: "+886", flag: "🇹🇼", aliases: ["Republic of China (Taiwan)","TW","Táiwān","Republic of China","中華民國","Zhōnghuá Mínguó","Chinese Taipei","TWN"] },
  { iso2: "TJ", name: "Tajikistan", dialCode: "+992", flag: "🇹🇯", aliases: ["Republic of Tajikistan","TJ","Toçikiston","Ҷумҳурии Тоҷикистон","Çumhuriyi Toçikiston","TJK"] },
  { iso2: "TZ", name: "Tanzania", dialCode: "+255", flag: "🇹🇿", aliases: ["United Republic of Tanzania","TZ","Tanzania, United Republic of","Jamhuri ya Muungano wa Tanzania","TZA"] },
  { iso2: "TH", name: "Thailand", dialCode: "+66", flag: "🇹🇭", aliases: ["Kingdom of Thailand","TH","Prathet","Thai","ราชอาณาจักรไทย","Ratcha Anachak Thai","THA"] },
  { iso2: "TL", name: "Timor-Leste", dialCode: "+670", flag: "🇹🇱", aliases: ["Democratic Republic of Timor-Leste","TL","East Timor","Timor","República Democrática de Timor-Leste","Repúblika Demokrátika Timór-Leste","Timór Lorosa'e","Timor Lorosae","TLS"] },
  { iso2: "TG", name: "Togo", dialCode: "+228", flag: "🇹🇬", aliases: ["Togolese Republic","TG","Togolese","République Togolaise","TGO"] },
  { iso2: "TK", name: "Tokelau", dialCode: "+690", flag: "🇹🇰", aliases: ["TK","TKL"] },
  { iso2: "TO", name: "Tonga", dialCode: "+676", flag: "🇹🇴", aliases: ["Kingdom of Tonga","TO","TON"] },
  { iso2: "TT", name: "Trinidad and Tobago", dialCode: "+1", flag: "🇹🇹", aliases: ["Republic of Trinidad and Tobago","TT","TTO"] },
  { iso2: "TN", name: "Tunisia", dialCode: "+216", flag: "🇹🇳", aliases: ["Tunisian Republic","TN","Republic of Tunisia","al-Jumhūriyyah at-Tūnisiyyah","TUN"] },
  { iso2: "TR", name: "Türkiye", dialCode: "+90", flag: "🇹🇷", aliases: ["Republic of Türkiye","TR","Turkiye","Republic of Turkey","Türkiye Cumhuriyeti","TUR"] },
  { iso2: "TM", name: "Turkmenistan", dialCode: "+993", flag: "🇹🇲", aliases: ["TM","TKM"] },
  { iso2: "TC", name: "Turks and Caicos Islands", dialCode: "+1", flag: "🇹🇨", aliases: ["TC","TCA"] },
  { iso2: "TV", name: "Tuvalu", dialCode: "+688", flag: "🇹🇻", aliases: ["TV","TUV"] },
  { iso2: "UG", name: "Uganda", dialCode: "+256", flag: "🇺🇬", aliases: ["Republic of Uganda","UG","Jamhuri ya Uganda","UGA"] },
  { iso2: "UA", name: "Ukraine", dialCode: "+380", flag: "🇺🇦", aliases: ["UA","Ukrayina","UKR"] },
  { iso2: "GB", name: "United Kingdom", dialCode: "+44", flag: "🇬🇧", aliases: ["United Kingdom of Great Britain and Northern Ireland","GB","UK","Great Britain","GBR"] },
  { iso2: "US", name: "United States", dialCode: "+1", flag: "🇺🇸", aliases: ["United States of America","US","USA"] },
  { iso2: "VI", name: "United States Virgin Islands", dialCode: "+1", flag: "🇻🇮", aliases: ["Virgin Islands of the United States","VI","Virgin Islands, U.S.","VIR"] },
  { iso2: "UY", name: "Uruguay", dialCode: "+598", flag: "🇺🇾", aliases: ["Oriental Republic of Uruguay","UY","República Oriental del Uruguay","URY"] },
  { iso2: "UZ", name: "Uzbekistan", dialCode: "+998", flag: "🇺🇿", aliases: ["Republic of Uzbekistan","UZ","O‘zbekiston Respublikasi","Ўзбекистон Республикаси","UZB"] },
  { iso2: "VU", name: "Vanuatu", dialCode: "+678", flag: "🇻🇺", aliases: ["Republic of Vanuatu","VU","Ripablik blong Vanuatu","République de Vanuatu","VUT"] },
  { iso2: "VA", name: "Vatican City", dialCode: "+39", flag: "🇻🇦", aliases: ["Vatican City State","VA","Holy See (Vatican City State)","Vatican","Stato della Città del Vaticano","VAT"] },
  { iso2: "VE", name: "Venezuela", dialCode: "+58", flag: "🇻🇪", aliases: ["Bolivarian Republic of Venezuela","VE","Venezuela, Bolivarian Republic of","República Bolivariana de Venezuela","VEN"] },
  { iso2: "VN", name: "Vietnam", dialCode: "+84", flag: "🇻🇳", aliases: ["Socialist Republic of Vietnam","VN","Cộng hòa Xã hội chủ nghĩa Việt Nam","Viet Nam","VNM"] },
  { iso2: "WF", name: "Wallis and Futuna", dialCode: "+681", flag: "🇼🇫", aliases: ["Territory of the Wallis and Futuna Islands","WF","Territoire des îles Wallis et Futuna","WLF"] },
  { iso2: "EH", name: "Western Sahara", dialCode: "+212", flag: "🇪🇭", aliases: ["Sahrawi Arab Democratic Republic","EH","Taneẓroft Tutrimt","ESH"] },
  { iso2: "YE", name: "Yemen", dialCode: "+967", flag: "🇾🇪", aliases: ["Republic of Yemen","YE","Yemeni Republic","al-Jumhūriyyah al-Yamaniyyah","YEM"] },
  { iso2: "ZM", name: "Zambia", dialCode: "+260", flag: "🇿🇲", aliases: ["Republic of Zambia","ZM","ZMB"] },
  { iso2: "ZW", name: "Zimbabwe", dialCode: "+263", flag: "🇿🇼", aliases: ["Republic of Zimbabwe","ZW","ZWE"] },
];

/**
 * Dial code → the principal country for it, in libphonenumber's ordering
 * ("+1" → US, "+44" → GB, "+7" → RU). We store only the dial code, so this
 * is what a saved number renders as when the code is shared.
 */
export const PRIMARY_COUNTRY_BY_DIAL_CODE: Record<string, string> = {
  "+1": "US",
  "+20": "EG",
  "+211": "SS",
  "+212": "MA",
  "+213": "DZ",
  "+216": "TN",
  "+218": "LY",
  "+220": "GM",
  "+221": "SN",
  "+222": "MR",
  "+223": "ML",
  "+224": "GN",
  "+225": "CI",
  "+226": "BF",
  "+227": "NE",
  "+228": "TG",
  "+229": "BJ",
  "+230": "MU",
  "+231": "LR",
  "+232": "SL",
  "+233": "GH",
  "+234": "NG",
  "+235": "TD",
  "+236": "CF",
  "+237": "CM",
  "+238": "CV",
  "+239": "ST",
  "+240": "GQ",
  "+241": "GA",
  "+242": "CG",
  "+243": "CD",
  "+244": "AO",
  "+245": "GW",
  "+246": "IO",
  "+248": "SC",
  "+249": "SD",
  "+250": "RW",
  "+251": "ET",
  "+252": "SO",
  "+253": "DJ",
  "+254": "KE",
  "+255": "TZ",
  "+256": "UG",
  "+257": "BI",
  "+258": "MZ",
  "+260": "ZM",
  "+261": "MG",
  "+262": "RE",
  "+263": "ZW",
  "+264": "NA",
  "+265": "MW",
  "+266": "LS",
  "+267": "BW",
  "+268": "SZ",
  "+269": "KM",
  "+27": "ZA",
  "+290": "SH",
  "+291": "ER",
  "+297": "AW",
  "+298": "FO",
  "+299": "GL",
  "+30": "GR",
  "+31": "NL",
  "+32": "BE",
  "+33": "FR",
  "+34": "ES",
  "+350": "GI",
  "+351": "PT",
  "+352": "LU",
  "+353": "IE",
  "+354": "IS",
  "+355": "AL",
  "+356": "MT",
  "+357": "CY",
  "+358": "FI",
  "+359": "BG",
  "+36": "HU",
  "+370": "LT",
  "+371": "LV",
  "+372": "EE",
  "+373": "MD",
  "+374": "AM",
  "+375": "BY",
  "+376": "AD",
  "+377": "MC",
  "+378": "SM",
  "+380": "UA",
  "+381": "RS",
  "+382": "ME",
  "+383": "XK",
  "+385": "HR",
  "+386": "SI",
  "+387": "BA",
  "+389": "MK",
  "+39": "IT",
  "+40": "RO",
  "+41": "CH",
  "+420": "CZ",
  "+421": "SK",
  "+423": "LI",
  "+43": "AT",
  "+44": "GB",
  "+45": "DK",
  "+46": "SE",
  "+47": "NO",
  "+48": "PL",
  "+49": "DE",
  "+500": "FK",
  "+501": "BZ",
  "+502": "GT",
  "+503": "SV",
  "+504": "HN",
  "+505": "NI",
  "+506": "CR",
  "+507": "PA",
  "+508": "PM",
  "+509": "HT",
  "+51": "PE",
  "+52": "MX",
  "+53": "CU",
  "+54": "AR",
  "+55": "BR",
  "+56": "CL",
  "+57": "CO",
  "+58": "VE",
  "+590": "GP",
  "+591": "BO",
  "+592": "GY",
  "+593": "EC",
  "+594": "GF",
  "+595": "PY",
  "+596": "MQ",
  "+597": "SR",
  "+598": "UY",
  "+599": "CW",
  "+60": "MY",
  "+61": "AU",
  "+62": "ID",
  "+63": "PH",
  "+64": "NZ",
  "+65": "SG",
  "+66": "TH",
  "+670": "TL",
  "+672": "NF",
  "+673": "BN",
  "+674": "NR",
  "+675": "PG",
  "+676": "TO",
  "+677": "SB",
  "+678": "VU",
  "+679": "FJ",
  "+680": "PW",
  "+681": "WF",
  "+682": "CK",
  "+683": "NU",
  "+685": "WS",
  "+686": "KI",
  "+687": "NC",
  "+688": "TV",
  "+689": "PF",
  "+690": "TK",
  "+691": "FM",
  "+692": "MH",
  "+7": "RU",
  "+81": "JP",
  "+82": "KR",
  "+84": "VN",
  "+850": "KP",
  "+852": "HK",
  "+853": "MO",
  "+855": "KH",
  "+856": "LA",
  "+86": "CN",
  "+880": "BD",
  "+886": "TW",
  "+90": "TR",
  "+91": "IN",
  "+92": "PK",
  "+93": "AF",
  "+94": "LK",
  "+95": "MM",
  "+960": "MV",
  "+961": "LB",
  "+962": "JO",
  "+963": "SY",
  "+964": "IQ",
  "+965": "KW",
  "+966": "SA",
  "+967": "YE",
  "+968": "OM",
  "+970": "PS",
  "+971": "AE",
  "+972": "IL",
  "+973": "BH",
  "+974": "QA",
  "+975": "BT",
  "+976": "MN",
  "+977": "NP",
  "+98": "IR",
  "+992": "TJ",
  "+993": "TM",
  "+994": "AZ",
  "+995": "GE",
  "+996": "KG",
  "+998": "UZ",
};
